### PR TITLE
removed the resting and flat shadows

### PR DESCRIPTION
**Pull request by lukasoppermann**
Hey @acstll as discussed with Julia and Joscha we want to remove the tokens for unused shadows (they may be added later if we decide we use them in our components).

Before merging please clarify with joscha again (I already did) and verify yourself that no `flat` or `resting` shadows are used.

### CODE REVIEW

**Comment by acstll** [comment]
@lukasoppermann `resting/standard` is used by default in [the thumb of the Slider](https://github.com/telekom/scale/blob/main/packages/components/src/components/slider/slider.css#L16).

image

If we removed `resting`, which token should we replace it with?

@maomaoZH could you be so kind and check what shadow tokens are being used directly in your project?

**Review by acstll — CHANGES_REQUESTED** [review]
@lukasoppermann please add a Changefile before merging (for the changelog), the message could be something like "Remove shadow/flat and shadow/resting tokens" 🙏 

Apart from that, all 👌 

---
`npm run change` — don't forget to pick `prerelease` for the change type

**Comment by maomaoZH** [comment]
>could you be so kind and check what shadow tokens are being used directly in your project?

`--telekom-shadow-raised-standard` this is the token we are using

**Comment by JoschaIco** [comment]
I also updated the slider in sketch.

**Pull request merged**
