### PR TITLE
use legacy color token ids

### PR DESCRIPTION
**Pull request by felix-ico**

### CODE REVIEW

**Comment by acstll** [comment]
Maybe we need to revert this. Let's not merge yet.

**Comment by felix-ico** [comment]
ah i guess that's why you wanted a different PR....i can still open a separate pr for this

**Comment by acstll** [comment]
> ah i guess that's why you wanted a different PR....i can still open a separate pr for this

yes, please, we need a separate PR 🙏 🙏

**Comment by felix-ico** [comment]
removed the code from here and added it to this PR https://github.com/telekom/design-tokens/pull/153

**Review by acstll — APPROVED** [review]

**Pull request merged**
