### PR TITLE
UI color restructure

### PR DESCRIPTION
**Pull request by lukasoppermann**
Hey @JoschaIco @acstll,

this is the update @JoschaIco and I discussed.

It required some changes in figma so it would be neat if we could merge this soon.

@acstll can you maybe do a test build and test it with the scale components to see if the removed styles are missing somewhere?

### CODE REVIEW

**Comment by acstll** [comment]
@lukasoppermann yes, we can test locally.

We'll get back with results (and do my review)… 🤓

**Comment by acstll** [comment]
@lukasoppermann we will need to update/rename all `ui` tokens in Scale, since all names changed. But that is fine 👍

This table should summarise all changes, that we can use to document the update. Can you please confirm this is correct?

| status | previous name | new name | value |
|--------|---------------|----------|-------|
| renamed | additional-base | base | #ffffff |
| renamed | additional-subtle | subtle | #f7f7f8 |
| renamed | additional-light | faint | #e7e7e9 |
| renamed | additional-regular | regular | #929296 |
| renamed | additional-strong | strong | #747478 |
| renamed | additional-extra-strong | extra-strong | #242426 |
| renamed | solid-disabled | disabled | #d0d0d2 |
| renamed | outlined-border-standard | border-standard | hsla(0, 0%, 0%, 0.44) |
| renamed | outlined-border-hovered | border-hovered | hsla(0, 0%, 0%, 0.71) |
| renamed | outlined-border-pressed | border-pressed | hsla(0, 0%, 0%, 0.71) |
| renamed | outlined-border-disabled | border-disabled | hsla(0, 0%, 0%, 0.14) |
| removed | outlined-border-active | ❌ | hsla(0, 0%, 0%, 0.71) |
| renamed | outlined-fill-standard | state-fill-standard: hsla(0, 0%, 0%, 0);
| renamed | outlined-fill-hovered | state-fill-hovered: hsla(0, 0%, 0%, 0.07);
| renamed | ghost-hovered-inverted | state-fill-hovered-inverted | hsla(0, 0%, 100%, 0.14) |
| renamed | outlined-fill-pressed | state-fill-pressed: hsla(0, 0%, 0%, 0.21);
| renamed | ghost-pressed-inverted | state-fill-pressed-inverted | hsla(0, 0%, 100%, 0.21) |
| removed | outlined-fill-active | ❌ | hsla(0, 0%, 0%, 0.21) |
| removed | outlined-fill-disabled | ❌ | hsla(0, 0%, 100%, 0) |
| removed | ghost-active | ❌ | hsla(0, 0%, 0%, 0.21) |
| removed | ghost-hovered | ❌ | hsla(0, 0%, 0%, 0.07) |
| removed | ghost-pressed | ❌ | hsla(0, 0%, 0%, 0.21) |
| removed | solid-standard | ❌ | #929296 |
| removed | solid-hovered | ❌ | #747478 |
| removed | solid-pressed | ❌ | #242426 |

**Comment by lukasoppermann** [comment]
Generally yes.

Some notes, you should replace the following tokens like this:

previous | new
---|---
outlined-border-active | border-pressed
outlined-fill-active | state-fill-pressed
outlined-fill-disabled | outlined-fill-standard or none
ghost-active | state-fill-pressed
ghost-pressed | state-fill-pressed
ghost-hovered | state-fill-hovered
solid-standard | regular
solid-hovered | strong
solid-pressed | extra-strong

**Comment by JoschaIco** [comment]
I added the replacements to the table:

status | previous name | new name | value | replace with
-- | -- | -- | -- | --
renamed | additional-base | base | #ffffff  | –
renamed | additional-subtle | subtle | #f7f7f8 | –
renamed | additional-light | faint | #e7e7e9 | –
renamed | additional-regular | regular | #929296 | –
renamed | additional-strong | strong | #747478 | –
renamed | additional-extra-strong | extra-strong | #242426 | –
renamed | solid-disabled | disabled | #d0d0d2 | –
renamed | outlined-border-standard | border-standard | hsla(0, 0%, 0%, 0.44) | –
renamed | outlined-border-hovered | border-hovered | hsla(0, 0%, 0%, 0.71) | –
renamed | outlined-border-pressed | border-pressed | hsla(0, 0%, 0%, 0.71) | –
renamed | outlined-border-disabled | border-disabled | hsla(0, 0%, 0%, 0.14) | –
removed | outlined-border-active | ❌ | hsla(0, 0%, 0%, 0.71) | border-pressed 
renamed | outlined-fill-standard | state-fill-standard: hsla(0, 0%, 0%, 0);  | – 
renamed | outlined-fill-hovered | state-fill-hovered: hsla(0, 0%, 0%, 0.07);  | – 
renamed | ghost-hovered-inverted | state-fill-hovered-inverted | hsla(0, 0%, 100%, 0.14)  | –
renamed | outlined-fill-pressed | state-fill-pressed: hsla(0, 0%, 0%, 0.21);  | –
renamed | ghost-pressed-inverted | state-fill-pressed-inverted | hsla(0, 0%, 100%, 0.21) | –
removed | outlined-fill-active | ❌ | hsla(0, 0%, 0%, 0.21)  | state-fill-pressed
removed | outlined-fill-disabled | ❌ | hsla(0, 0%, 100%, 0) | none
removed | ghost-active | ❌ | hsla(0, 0%, 0%, 0.21) | state-fill-pressed
removed | ghost-hovered | ❌ | hsla(0, 0%, 0%, 0.07) | state-fill-hovered
removed | ghost-pressed | ❌ | hsla(0, 0%, 0%, 0.21) | state-fill-pressed
removed | solid-standard | ❌ | #929296 | regular
removed | solid-hovered | ❌ | #747478 | strong
removed | solid-pressed | ❌ | #242426 | extra-strong

<br class="Apple-interchange-newline">

**Pull request merged**
